apiVersion: apps/v1
kind: Deployment
metadata:
  name: kni-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kni-operator
  template:
    metadata:
      labels:
        name: kni-operator
    spec:
      serviceAccountName: kni-operator
      containers:
        - name: kni-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - kni-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KNI_CLUSTER_NAME
              value: "kni-cluster"
            - name: KNI_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "kni-operator"
